# Default Configuration for Surgical Phase Recognition
# This is the baseline configuration for training surgical phase recognition models

model:
  name: "swin3d"
  num_classes: 11
  input_size: [224, 224]
  clip_length: 16
  embed_dim: 96
  depths: [2, 2, 6, 2]
  num_heads: [3, 6, 12, 24]
  dropout: 0.1
  pretrained: true
  
  # Model-specific parameters
  hidden_size: 256
  bidirectional: true
  backbone: "resnet50"
  use_attention: true

data:
  data_root: "/path/to/data"
  train_annotation: "train_annotations.csv"
  val_annotation: "val_annotations.csv"
  test_annotation: "test_annotations.csv"
  
  # Video preprocessing
  target_fps: null
  max_frames: null
  sampling_strategy: "uniform"
  
  # Data loading
  batch_size: 8
  num_workers: 4
  pin_memory: true
  
  # Augmentation
  augment_prob: 0.5
  use_advanced_augmentation: true
  
  # Phase mapping
  phase_mapping:
    "Incision": 0
    "Viscous Agent Injection": 1
    "Rhexis": 2
    "Hydrodissection": 3
    "Phacoemulsification": 4
    "Irrigation and Aspiration": 5
    "Capsule Polishing": 6
    "Lens Implant Setting": 7
    "Viscous Agent Removal": 8
    "Suturing": 9
    "Tonifying Antibiotics": 10

training:
  max_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.0001
  optimizer: "adamw"
  scheduler: "cosine"
  
  # Early stopping
  patience: 15
  min_delta: 0.001
  
  # Checkpointing
  save_top_k: 3
  monitor: "val_f1"
  mode: "max"
  
  # Gradient settings
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  
  # Mixed precision
  precision: "16-mixed"
  
  # Validation
  val_check_interval: 1.0
  check_val_every_n_epoch: 1

experiment:
  name: "surgical_phase_recognition"
  version: null
  description: ""
  tags: []
  
  # Logging
  log_every_n_steps: 50
  log_model: true
  
  # Wandb settings
  use_wandb: false
  wandb_project: "surgical-phase-recognition"
  wandb_entity: null
  
  # Output directories
  output_dir: "./outputs"
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"
  
  # Reproducibility
  seed: 42
  deterministic: true
