# TeCNO Model Configuration
# Advanced multi-stage model with temporal consistency

model:
  name: "tecno"
  num_classes: 11
  input_size: [224, 224]
  clip_length: 16
  hidden_size: 512
  temporal_window: 16
  dropout: 0.3
  use_attention: true
  pretrained: true
  backbone: "resnet50"

data:
  data_root: "/path/to/data"
  train_annotation: "train_annotations.csv"
  val_annotation: "val_annotations.csv"
  test_annotation: "test_annotations.csv"
  
  # Video preprocessing
  target_fps: null
  max_frames: null
  sampling_strategy: "uniform"
  
  # Data loading
  batch_size: 6
  num_workers: 6
  pin_memory: true
  
  # Augmentation
  augment_prob: 0.6
  use_advanced_augmentation: true

training:
  max_epochs: 180
  learning_rate: 0.00003
  weight_decay: 0.0001
  optimizer: "adamw"
  scheduler: "cosine"
  
  # Early stopping
  patience: 20
  min_delta: 0.0005
  
  # Checkpointing
  save_top_k: 3
  monitor: "val_f1"
  mode: "max"
  
  # Gradient settings
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  
  # Mixed precision
  precision: "16-mixed"
  
  # Validation
  val_check_interval: 1.0
  check_val_every_n_epoch: 1

experiment:
  name: "tecno_model"
  description: "TeCNO multi-stage model with temporal consistency"
  tags: ["advanced", "tecno", "multi_stage", "temporal_consistency"]
  
  # Logging
  log_every_n_steps: 30
  log_model: true
  
  # Wandb settings
  use_wandb: true
  wandb_project: "surgical-phase-recognition"
  
  # Output directories
  output_dir: "./outputs/tecno"
  checkpoint_dir: "./checkpoints/tecno"
  log_dir: "./logs/tecno"
  
  # Reproducibility
  seed: 42
  deterministic: true
