# Processing Configuration for Cataract-LMM Dataset
# Based on process_video.sh reference script methodology
# 
# This configuration implements the specific processing approach found in
# process_video.sh for phacoemulsification cataract surgery videos.
# No hospital-specific assumptions are made beyond what's documented 
# in the Cataract-LMM research paper.

# General Processing Configuration  
processing:
  quality_check_enabled: true
  deidentification_enabled: true
  processing_enabled: true
  metadata_extraction_enabled: true
  parallel_processing: false
  max_workers: 4
  output_format: "mp4"
  quality_threshold: 60.0
  processing_crf: 23
  target_resolution: null  # Preserve original resolution
  target_fps: null         # Preserve original fps
  preserve_audio: true     # Copy audio as per reference script
  backup_originals: true
  log_level: "INFO"

# Reference Script Processing Settings (from process_video.sh)
reference_processing:
  enabled: true
  crop_filter: "crop=268:58:6:422"    # Exact crop from process_video.sh
  blur_filter: "avgblur=10"           # Exact blur from process_video.sh  
  overlay_position: "6:422"           # Exact overlay position
  filter_complex: "[0:v]crop=268:58:6:422,avgblur=10[fg];[0:v][fg]overlay=6:422[v]"
  map_video: "[v]"
  map_audio: "0:a"
  video_codec: "libx265"
  audio_codec: "copy" 
  crf_value: 23
  movflags: "+faststart"

# Video Preprocessing Configuration
preprocessing:
  standardize_resolution: false  # Preserve original
  standardize_fps: false         # Preserve original
  enhance_contrast: false        # Let reference processing handle
  reduce_noise: false           # Let reference processing handle
  stabilize_video: false
  crop_margins: [0, 0, 0, 0]
  brightness_adjustment: 0
  contrast_adjustment: 1.0
  saturation_adjustment: 1.0
  gamma_correction: 1.0

# Quality Control Configuration
quality_control:
  min_overall_score: 50.0
  min_focus_score: 40.0
  max_glare_percentage: 25.0
  min_exposure_score: 35.0
  max_motion_threshold: 25.0
  min_completeness_score: 60.0
  enable_focus_check: true
  enable_glare_check: true
  enable_exposure_check: true
  enable_motion_check: true
  enable_completeness_check: true

# De-identification Configuration
deidentification:
  remove_metadata: true
  remove_timestamps: true
  remove_watermarks: true
  remove_audio: false  # Preserve audio per reference script
  blur_patient_info: true
  remove_date_time: true
  hash_identifiers: true
  # Note: Reference script handles privacy through crop/blur filters

# FFmpeg Configuration (from process_video.sh)
ffmpeg:
  global_options: ["-y", "-hide_banner"]
  input_options: []
  filter_complex: "[0:v]crop=268:58:6:422,avgblur=10[fg];[0:v][fg]overlay=6:422[v]"
  map_options: ["-map", "[v]", "-map", "0:a"]
  video_codec: "libx265"
  audio_codec: "copy"
  crf: 23
  output_options: ["-movflags", "+faststart"]

# Batch Processing
batch:
  resume_capability: true
  progress_tracking: true
  error_handling: "continue"
  output_naming: "processed_{filename}"
  create_manifest: true

# Output Configuration
output:
  directory_structure: "flat"
  filename_prefix: "processed_"
  preserve_timestamps: false
  create_checksums: true
  generate_metadata: true
